kind: pipeline
type: docker
name: gopay

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: helloworld
    pull: if-not-exists
    image: hello-world

  - name: ci_1.13
    pull: if-not-exists
    image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    depends_on:
      - helloworld
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...

  - name: ci_1.14
    pull: if-not-exists
    image: golang:1.14
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    depends_on:
      - helloworld
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...

  - name: ci_1.15
    pull: if-not-exists
    image: golang:1.15
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    depends_on:
      - helloworld
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag
