kind: pipeline
type: docker
name: gopay

platform:
  os: linux
  arch: amd64

steps:
  - name: ci
    image: golang:1.14
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
